name: Build KMP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build iOS Desktop
    runs-on: macos-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
